services:
  run_test:
    build:
      context: .
      dockerfile: Dockerfile_2
    volumes:
      - ./:/Test
    command: pytest -sv --alluredir=allure-results
    working_dir: /Test
  report:
    build:
      context: .
      dockerfile: Dockerfile_2
    volumes:
      - ./:/Test
    command: allure-generate allure-results --clean -o allure-report